version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest   # pgvector가 포함된 PostgreSQL 이미지
    container_name: momo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p1234
      POSTGRES_DB: momo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 확장 자동 설치

  redis:
    image: redis:7
    container_name: momo_redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
      container_name: momo_elasticsearch
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false  # 인증 비활성화
        - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 메모리 제한
        - xpack.security.transport.ssl.enabled=false
      ports:
        - "9200:9200"
      volumes:
        - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: momo_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  pgdata:
  esdata:
